### ISSUE TITLE
支不支持mac呢?

### ISSUE THREAD

**Issue by taizilongxu** [egoist/image-cli#1]
osx el 试了下, 出现下面的错误
<img width="786" alt="2015-12-20 7 51 19" src="https://cloud.githubusercontent.com/assets/4475914/11917828/2fd99caa-a753-11e5-9274-377889f905f9.png">

**Comment by egoist** [comment]
重新安装试试?

**Comment by egoist** [comment]
看来是个bug

**Comment by egoist** [comment]
cc @djyde

**Comment by egoist** [comment]
@taizilongxu @djyde 0.0.22 解决了，重新安装一下。都是 `yeoman` 的锅，自动初始化的包里面有 files 这个属性导致 `lib` 文件夹没被包括进去。 https://docs.npmjs.com/files/package.json#files

**Comment by taizilongxu** [comment]
OK 已正常 : -)
